E2E testing
baochanh18/nest_backend_base pull request #3
Opened 2023-04-16 14:34 UTC by baochanh18

2023-04-17 02:54 UTC, tuananhhedspibkclone requested changes

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/app.module.ts
> +    // MessageModule,
🔥

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/domain/factory/SampleFactory.spec.ts
> +      // Act
🔥

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/domain/factory/SampleFactory.spec.ts
> +      // Assert
🔥

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/domain/factory/SampleFactory.spec.ts
> +      // Act
```ts
const sample = factory.create(options);
```
↑をbeforeAllに移動してください。

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/domain/factory/SampleFactory.spec.ts
> +      // Act
🔥

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/domain/factory/SampleFactory.spec.ts
> +      // Act
```ts
const sample = factory.reconstitute(properties);
```

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/domain/factory/SampleFactory.spec.ts
> +      // Act
↑をbeforeAllに移動してください。

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/domain/factory/SampleFactory.spec.ts
> +      // Assert
🔥

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on libs/Testing.ts
> +  return { testModule, app };
`testModules`の中に `testModule`と `app`が存在してるんで、ちょっと変じゃない？？？

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/application/command/SampleHandler.spec.ts
> +    const sample = {
```suggestion
    const mockSampleAggregate = {
```

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/application/command/SampleHandler.spec.ts
>        await expect(handler.execute(command)).resolves.toEqual(undefined);
```ts
let result;
beforeAll(async () => {
  result = await handler.execute(command);
});

it('blah blah blah', () => {
  expect(result).toEqual(null);
});

```

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/domain/factory/SampleFactory.spec.ts
> +      // Assert
```ts
const sample = factory.create(options);
```
↑をbeforeAllに移動してください。

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/domain/service/SampleDomainService.spec.ts
> +    sample = { sampleErrorEvent: jest.fn() } as unknown as Sample;
ふむ、Sample集約をmockすればそれの全部のメソッドをmockして欲しいです。

`as unknown as Sample`はちょっとキモイ。

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/application/command/SampleHandler.spec.ts
> +    const sample = {
ふむ、Sample集約をmockすればそれの全部のメソッドをmockして欲しいです。

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/query/SampleQueryImplement.spec.ts
> +    testConnection = await testModules(providers);
`testConnection`名前はちょっと変。。。

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/query/SampleQueryImplement.spec.ts
> +        entity.id = 1;
直接話しておきました。`testData/`フォルダにサンプルデータファイルを作成し、`testModules`初期化時にサンプルデータをテスト用ベータベースに入れる。

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/query/SampleQueryImplement.spec.ts
> +        entity.id = 1;
直接話しておきました。`testData/`フォルダにサンプルデータファイルを作成し、`testModules`初期化時にサンプルデータをテスト用ベータベースに入れる。

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +    await writeConnection.manager.delete(SampleEntity, {});
テストデータベースにconnectionをcloseが要らない？？？？

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +        } as unknown as SampleAggregate;
`class-transformer`の `plainToClass`を使ってください、基本的な目的はプレインオブジェクトから `Entityクラス`にデータ型変換です。
例:
https://github.com/air-closet/bridge-api/blob/5207cbde26525c4b90305c379b751755695a548d/src/usecase/bulk-update-item-sku-with-barcode/testData/index.ts#L9

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +      it('saved successfully', async () => {
```suggestion
      it('saved to DB successfully', () => {
```

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +        const data = [{ id: 1 }, { id: 2 }] as unknown as SampleAggregate[];
class-transformerの plainToClassを使ってください

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +        entities = await writeConnection.manager.find(SampleEntity);
`find`関数に特定の条件がない？？？

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +        entities = await writeConnection.manager.find(SampleEntity);
`find`関数に特定の条件がない？？？

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +      it('saved successfully', async () => {
```suggestion
      it('saved to DB successfully', () => {
```

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +      it('should return null', async () => {
```suggestion
      it('should return null', () => {
```

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +        const data = { id: 1 } as unknown as SampleAggregate;
サンプルデータファイルに入れていください。

2023-04-17 02:54 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +      it('id is matching', async () => {
```suggestion
      it('id is matching', () => {
```

2023-04-17 08:35 UTC, baochanh18 commented on libs/Testing.ts
> +  return { testModule, app };
変数変わりました。

2023-04-17 08:36 UTC, baochanh18 commented on src/app.module.ts
> +    // MessageModule,
まだ使わないので、コメントアウトしました。

2023-04-17 08:37 UTC, baochanh18 commented on src/sample/application/command/SampleHandler.spec.ts
> +    const sample = {
修正しました。

2023-04-17 08:51 UTC, baochanh18 commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +        entities = await writeConnection.manager.find(SampleEntity);
これはTypeormのFindAllという感じです。

2023-04-17 09:12 UTC, baochanh18 commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +        entities = await writeConnection.manager.find(SampleEntity);
これはTypeormのFindAllという感じです。

2023-04-18 05:35 UTC, tuananhhedspibkclone requested changes

2023-04-18 05:35 UTC, tuananhhedspibkclone commented on libs/Testing.ts
> +export const testingConnection = async (providers: Provider[]) => {
```suggestion
export const testingConfigure = async (providers: Provider[]) => {
```

2023-04-18 05:35 UTC, tuananhhedspibkclone commented on libs/libTesting/RedisModule.spec.ts
> +      imports: [RedisModule],
https://github.com/baochanh18/nest_backend_base/blob/b9c06cdc64405d82f9c10a6b3a639ebede15d3be/libs/Testing.ts#L17
↑に`RedisModule`追加したらいいじゃない？？？
追加すれば `testingConfigure `を使って欲しいです。

2023-04-18 05:35 UTC, tuananhhedspibkclone commented on libs/libTesting/RedisModule.spec.ts
> +    await redisClient.set(key, value);
テストデータファイル準備して欲しい。

2023-04-18 05:35 UTC, tuananhhedspibkclone commented on src/sample/application/command/SampleHandler.spec.ts
> +    it('should execute SampleCommand', () => {
itを分けて欲しい、
```ts
it('Aggregate methods are executed', () => {
  expect(mockSample.compareId).toBeCalledTimes(1);
  expect(mockSample.commit).toBeCalledTimes(1);
});

it('Execute result is as expected', () => {
  expect(executeResult).toEqual(undefined);
});

it('findById function is called', () => {
  expect(repository.findById).toBeCalledTimes(1);
  expect(repository.findById).toBeCalledWith(1);
});
```

2023-04-18 05:35 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/query/SampleQueryImplement.spec.ts
> +    await repository.save(sampleData);
```ts
await writeConnection.manager.save(SampleEntity, sampleData);
```
みたい感じに修正して欲しい

2023-04-18 05:35 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/testdata/index.ts
> +const multipleSampleData: SampleAggregate[] = plainToClass(SampleAggregate, [
```suggestion
const sampleData: SampleAggregate[] = plainToClass(SampleAggregate, [
```
だけでいい、`singleSampleData `が要らん。

2023-04-18 05:35 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +  let appConnection: INestApplication;
```suggestion
  let app: INestApplication;
```

2023-04-18 05:35 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/query/SampleQueryImplement.spec.ts
> +  let appConnection: INestApplication;
```suggestion
  let app: INestApplication;
```

2023-04-18 05:35 UTC, tuananhhedspibkclone commented on src/sample/domain/factory/SampleFactory.spec.ts
> +  let appConnection: INestApplication;
```suggestion
  let app: INestApplication;
```

2023-04-18 05:35 UTC, tuananhhedspibkclone commented on src/sample/application/command/SampleHandler.spec.ts
> +  let appConnection: INestApplication;
```suggestion
  let app: INestApplication;
```

2023-04-18 06:25 UTC, baochanh18 commented on libs/libTesting/RedisModule.spec.ts
> +      imports: [RedisModule],
@tuananhhedspibkclone 
Redisテストするだけなので、別のModuleは不要を思っています。
テストスピードも速くなっている。

2023-04-18 08:00 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +      const value = 'test-value';
サンプルデータに移動

2023-04-18 09:52 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/testdata/index.ts
> +};
```suggestion
const sampleKeyValues = [
  {
    key: 'test-key-1',
    value: 'test-value-1',
   },
   {
     key: 'test-key-2',
     value: 'test-value-2',
   }
];
```

2023-04-19 05:46 UTC, merged

2023-04-19 05:47 UTC, tuananhhedspibkclone approved these changes

2023-04-19 06:56 UTC, baochanh18 commented
![LGTM](https://images.lgtmgen.org/4d4935b9-0d4f-451c-be91-c5439193cfbb)