add sample detail
baochanh18/nest_backend_base pull request #4
Opened 2023-04-21 08:49 UTC by baochanh18

2023-04-21 10:13 UTC, tuananhhedspibkclone requested changes

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on libs/FactoryHelper.ts
> +export abstract class FactoryHelper {
```suggestion
export abstract class BaseFactory {
```

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/SamplesModule.ts
> +import { SampleDetailFactory } from './domain/factory/SampleDetailFactory';
不要

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/SamplesModule.ts
> +const domain = [SampleDomainService, SampleFactory, SampleDetailFactory];
SampleDetailFactory削除

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/application/command/SampleHandler.spec.ts
> +import { SampleDetailFactory } from '../../domain/factory/SampleDetailFactory';
不要

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/domain/aggregate/sampleDetail/index.spec.ts
> +import { InternalServerErrorException } from '@nestjs/common';
このファイルは不要

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/domain/aggregate/sampleDetail/index.ts
> +import { AggregateRoot } from '@nestjs/cqrs';
不要

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/query/SampleQueryImplement.ts
> +      .leftJoinAndSelect('sample.sampleDetail', 'sampleDetail');
特定のカルムのみSELECTする

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +import { plainToClass } from 'class-transformer/build/package';
```suggestion
import { plainToClass } from 'class-transformer';
```

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.ts
>    private modelToEntity(model: Sample): SampleEntity {
この関数は不要

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.ts
>    private entityToModel(entity: SampleEntity): Sample {
この関数も不要

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.ts
> +      .leftJoinAndSelect('sample.sampleDetail', 'sampleDetail');
特定のカラムのみSELECT

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.ts
>    private modelToEntity(model: Sample): SampleEntity {
factory使ってみて

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.ts
>    private entityToModel(entity: SampleEntity): Sample {
factory使ってみて

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/testdata/index.ts
> +    sampleDetail: plainToClass(SampleDetailAggregate, {
ここのplainToClassは不要

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/testdata/index.ts
> +    sampleDetail: plainToClass(SampleDetailAggregate, {
ここのplainToClassは不要

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/testdata/index.ts
> +    sampleDetail: plainToClass(SampleDetailAggregate, {
ここのplainToClassは不要

2023-04-21 10:13 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/testdata/index.ts
> +    sampleDetail: plainToClass(SampleDetailAggregate, {
ここのplainToClassは不要

2023-04-24 00:37 UTC, tuananhhedspibkclone requested changes

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/testdata/index.ts
> +const sampleData: SampleAggregate[] = plainToInstance(SampleAggregate, [
`plainToInstance`使ってる理由は？？？

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.ts
> +      ]);
```suggestion
      .select([
        'sample.id',
        'sample.createdAt',
        'sample.updatedAt',
        'sample.deletedAt',
        'sampleDetail.id',
        'sampleDetail.sampleId',
        'sampleDetail.content',
        'sampleDetail.createdAt',
        'sampleDetail.updatedAt',
      ])
      .leftJoin('sample.sampleDetail', 'sampleDetail');
```

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +          entitiy = plainToInstance(SampleEntity, await repository.findById(1));
```suggestion
          entity = plainToInstance(SampleEntity, await repository.findById(1));
```

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +          entitiy = plainToInstance(SampleEntity, await repository.findById(1));
`plainToInstance`使ってる理由は？？？

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/repository/SampleRepositoryImplement.spec.ts
> +          entitiy = plainToInstance(SampleEntity, await repository.findById(1));
`plainToInstance`使ってる理由は？？？

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/query/testdata/index.ts
> +const sampleData: SampleEntity[] = plainToInstance(SampleEntity, [
`plainToInstance`使ってる理由は？？？

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on src/sample/infrastructure/query/SampleQueryImplement.ts
> +      ]);
```suggestion
      .select([
        'sample.id',
        'sample.createdAt',
        'sample.updatedAt',
        'sample.deletedAt',
        'sampleDetail.id',
        'sampleDetail.sampleId',
        'sampleDetail.content',
        'sampleDetail.createdAt',
        'sampleDetail.updatedAt',
      ])
      .leftJoin('sample.sampleDetail', 'sampleDetail')
```

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on src/sample/domain/factory/index.ts
> +  createEntity(options: Sample): SampleEntity {
```suggestion
  createEntity(plainObj: Sample): SampleEntity {
```

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on src/sample/domain/factory/index.ts
> +  createEntityArray(options: Sample[]): SampleEntity[] {
```suggestion
  createEntityArray(plainObjs: Sample[]): SampleEntity[] {
```

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on src/sample/domain/aggregate/sampleDetail/index.spec.ts
> +import { SampleDetail, SampleDetailProperties } from '.';
このspecは要らない。

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on src/sample/domain/aggregate/sample.ts
> +import { Type as ClassTranformType } from 'class-transformer';
```suggestion
import { Type as ClassTransformType } from 'class-transformer';
```

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on src/sample/application/command/testdata/index.ts
> +const sampleDetailData = new SampleDetail({
```TS
const sampleData = plainToClass(SampleAggregate, {
  id: 1,
  createdAt: new Date(),
  updatedAt: new Date(),
  deletedAt: null,
  sampleDetail: {
    id: 1,
    sampleId: 1,
    content: 'test',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
});
```

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on package.json
> -    "class-transformer": "git+https://airClosetDev:3c8d59ccd2dcb6aa4e96887eb4a6bb20b023c56a@github.com/air-closet/class-transformer.git"
なんでアンインストールしてんの？？？

2023-04-24 00:37 UTC, tuananhhedspibkclone commented on libs/FactoryHelper.ts
> -import { plainToClass } from 'class-transformer';
なんで削除してんの？？？？

2023-04-24 01:38 UTC, baochanh18 commented on src/sample/infrastructure/repository/testdata/index.ts
> +const sampleData: SampleAggregate[] = plainToInstance(SampleAggregate, [
最新のclass-transfromerは使用しないです。

2023-04-24 01:46 UTC, baochanh18 commented on package.json
> -    "class-transformer": "git+https://airClosetDev:3c8d59ccd2dcb6aa4e96887eb4a6bb20b023c56a@github.com/air-closet/class-transformer.git"
インストールされの理由
https://github.com/baochanh18/nest_backend_base/blob/8a336772651a7f320049ec006de6e971ba8550c0/package.json#L48

2023-04-24 01:47 UTC, baochanh18 commented on libs/FactoryHelper.ts
> -import { plainToClass } from 'class-transformer';
Factoryで直接class-transformer使用しているので、削除しました。

2023-04-24 05:10 UTC, tuananhhedspibkclone requested changes

2023-04-24 05:10 UTC, tuananhhedspibkclone commented on README.md
> +This will start the containers in detached mode. You can then access the project at `http://localhost:3846`.
元に戻れ

2023-04-24 05:10 UTC, tuananhhedspibkclone commented on docker-compose.yml
> +      - 3846:80
元に戻れ

2023-04-24 05:10 UTC, tuananhhedspibkclone commented on libs/FactoryHelper.ts
> -import { plainToClass } from 'class-transformer';
OK

2023-04-24 05:10 UTC, tuananhhedspibkclone commented on src/config.ts
> +  readonly PORT = Number(process.env.PORT) || 3846;
元に戻れ

2023-04-24 05:25 UTC, merged